name: Generate Clash Config

on:
  schedule:
    - cron: '0 0 * * *'  # jalan tiap hari jam 00:00 UTC
  workflow_dispatch:      # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generate.py
        run: python generate.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add akun.yaml config.yaml
          git commit -m "Auto update Clash config $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push    - name: Test with pytest
      run: |
        pytest
